### ISSUE TITLE
Wrong system URL for HSLOC in 2 value sets

### ISSUE THREAD

**Issue by p9g** [cqframework/ecqm-content-r4-2022#5]
see
https://github.com/cqframework/ecqm-content-r4-2022/blob/master/input/vocabulary/valueset/external/valueset-2.16.840.1.113762.1.4.1029.205.json 
https://github.com/cqframework/ecqm-content-r4-2022/blob/master/input/vocabulary/valueset/external/valueset-2.16.840.1.113762.1.4.1029.206.json 

for example
{
      "system": "**http://terminology.hl7.org/CodeSystem/hsloc**",
      "version": "2020",
      "code": "1025-6",
      "display": "Trauma Critical Care"
    },

http://terminology.hl7.org/CodeSystem/hsloc says that the official URL is
https://www.cdc.gov/nhsn/cdaportal/terminology/codesystem/hsloc.html

https://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113762.1.4.1029.206/$expand returns 
{
      "system": "**https://www.cdc.gov/nhsn/cdaportal/terminology/codesystem/hsloc.html**",
      "version": "2022",
      "code": "1025-6",
      "display": "Trauma Critical Care"
    },

These expansions in this repo (and others on cqframework/ecqm-content-*) should be updated to use the correct system URL.

**Comment by p9g** [comment]
Also update valueset-2.16.840.1.114222.4.11.836.json and valueset-2.16.840.1.114222.4.11.837.json to use urn:oid:2.16.840.1.113883.6.238 instead of http://terminology.hl7.org/CodeSystem/PHRaceAndEthnicityCDC (more info in cqf-tooling#173)

**Comment by mholck** [comment]
Looks like the CDC Race and ethnicity system has changed to https://terminology.hl7.org/3.1.0/NamingSystem-CDCREC.html

Will update to use that rather than urn:oid:2.16.840.1.113883.6.238 unless that is an issue

**Comment by brynrhodes** [comment]
Fixed and committed
